name: Azure
values:
  - key: authHostUrl
    value: ''
  - key: leaderboardHostUrl
    value: ''
  - key: testPlayer
    value: ''
  - key: token
    value: ''
  - key: jwtSecret
    value: ''
color: 240
