name: Deploy Leaderboard Service

on:
  push:
    branches:
      - main
    paths:
      - "Didakt.Api.Leaderboard/**"
      - ".github/workflows/deploy-leaderboard.yml"
      - ".github/workflows/deploy-service-reusable.yml"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service-reusable.yml
    with:
      service-name: didakt-leaderboard
      project-dir: Didakt.Api.Leaderboard
    secrets: inherit