name: Deploy Auth Service

on:
  push:
    branches:
      - main
    paths:
      - "Didakt.Api.Auth/**"
      - ".github/workflows/deploy-auth.yml"
      - ".github/workflows/deploy-service-reusable.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service-reusable.yml
    with:
      service-name: didakt-auth
      project-dir: Didakt.Api.Auth
    secrets: inherit